# Generated by Django 2.2.5 on 2021-01-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('rooms', '0003_auto_20210125_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': '편의시설 관리'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': '시설 관리'},
        ),
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name_plural': '규칙 관리'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '객실 관리'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': '객실유형 관리'},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampedModel')),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
